calcs/depthBelowKeel2.js
NMEA0183 units often only report depth below transducer, so added
another below keel calc
=> Add depth below keel from belowTransducer

calcs/tankVolume.js, package.json
Still experimental, but should show the basics. Thanks for the PR to the node server (https://github.com/SignalK/signalk-server-node/pull/285). The example code 
```
plugin.schema = function() {
var tank_instances = _.keys(app.signalk.self.tanks)
return  {
type: "object",
required: [
],
properties: {
alarmState: {
title: "Tank",
type: "string",
default: "alarm",
"enum": tank_instances
}
}
}
}
``` 
would probably fit in index.js, not the calcs/file.js. That sort of messes up the split.
=> Tankcalibration (WIP)

calcs/cpa_tcpa.js, index.js
- Adding multiple zones in traffic notifications.
- I kept the checkbox `Send dangerous targets notifications` in global, easy to disable everything, and there is another one per zone.
- When loading, there is an update of the `traffic` configuration for users with an old configuration. The outdated values in the configuration are destroyed after the update.
- I ran `prettier-standard` only on `index.js` & `cpa_tcpa.js`.
=> feature: Adding multiple zones in traffic notifications

calcs/cpa_tcpa.js
Fix notification paths for CPA_TCPA to use vessel `uuid` and not the mmsi.
closes #34.
=> Fix notification paths for CPA_TCPA to use vessel uuid.

calcs/depthBelowSurface.js
added "design.draft.value.maximum" as an alternative reading of "design.draft.maximum.value" as is already the case in depthBelowKeel.js. The "Depth Below Surface" tick-box in the SignalK-plugin-config doesn't work otherwise.
=> fix: use design.draft.value.maximum for depthBelowSurface if available

calcs/depthBelowKeel2.js
This bug fix intends to fix issue https://github.com/SignalK/signalk-derived-data/issues/49
The change calculates `depth.belowKeel` using the current value for `depth.transducerToKeel`, rather than that value at server start-up. There are various cases where this value is not present at that time or changes later in time:
- Lifting keel
- `depth.transducerToKeel` source is not the server config, but a "live" source
- depth transducer is not in a fixed point
- etc
=> Bugfix: retrieve depth.transducerToKeel in calculation, not at start-up

calcs/cpa_tcpa.js
Convert both timestamps that are input for the calculation of secondsSinceVesselUpdate to epoch time. Background: Calculation of secondsSinceVesselUpdate failed with NaN since the format of the timestamps that are used for the calculation of secondsSinceVesselUpdate was inconsistent.
=> fix: Change input for calculation of secondsSinceVesselUpdate consistently to epoch time format

calcs/eta.js, calcs/steer_error.js
**eta.js**
I would like to add 'eta' to next waypoint to derived data.  this file creates:
'navigation.courseGreatCircle.nextPoint.eta' and delivers a date/time of arrival at the waypoint
**steer_error.js**
this file adds a few phrases for Steer Error, this being the difference between the desired direction and the actual direction.  there are 3 different phrases:
"navigation.courseGreatCircle.nextPoint.steerError" - this gives a value for the error with a positive or negative to suggest the direction
"navigation.courseGreatCircle.nextPoint.leftSteerError" - this gives a value for the error in the Port direction
"navigation.courseGreatCircle.nextPoint.rightSteerError" - this gives a value for the error in the Starboard direction
the right and left steer error are for use to help with …
=> ETA to next waypoint and steer error

calcs/courseData.js
Compute navigation.courseGreatCircle.bearingTrackMagnetic and navigation.courseGreatCircle.nextPoint.bearingMagnetic
These paths are required by  signalk-to-nmea0183 to produce the APB message
=> feature: Compute courseGreatCircle.bearingTrackMagnetic and nextPoint.bearingMagnetic

calcs/groundWind.js, calcs/trueWind.js
Set wind.angleTrueWater (TWA) and wind.angleTrueGround (GWA) identically to wind.angleApparent (AWA) in case wind.speedApparent (AWS) is smaller than 1e-9m/s. Background: Before for AWS=0 the plugin delivered wrong GWA and TWA since AWS=0 drove the arguments that are used for calculating the angles to zero.
=> fix: Assign TWA and GWA identically to AWA in case AWS is smaller than 1e-9m/s

calcs/magneticVariation.js, test/test.js
test for magneticVariation calc was failing because of change in predicted value.  
Test now allows for delta around predicted value using closeTo check.
=> Magnetic variation: handle MagVar drifting over time in test

calcs/vmg.js
VMG towards next waypoint was incorrectly based on headingTrue instead of courseOverGround (see issue #33).
=> fix: VMG towards waypoint based on courseOverGround instead of headingTrue

README.md, calcs/courseOverGroundMagnetic.js, calcs/courseOverGroundTrue.js, calcs/headingTrue.js, calcs/windDirectionMagnetic.js
Input value null should result in null output values.
Fixes #120.
=> fix: pass null through true/mag conversions

calcs/eta.js
in this PR:
1.  'navigation.courseGreatCircle.nextPoint.timeToGo' added a.  this is in Seconds per the spec. b.  the null value set to null vs "--"
2.  eta null value set to null vs "--"
See Forum post: https://forum.openmarine.net/showthread.php?tid=5017
=> Add nextPoint.timeToGo, set estimatedTimeOfArrival as null when not available

calcs/leeway.js
Fix issue with leeway calculation where roll is using the wrong path
Fix issue where calculated leeway is invalid if STW is 0
=> Fix issues with leeway calculation

calcs/moon.js
Fixes #122
Previous implementation retuned all moon path values as strings. Adjusted return types to correct types and added tests.
=> fix(moon): changed to type specific return values and added moon test

calcs/eta.js
Fixes #133.
The calculation uses:
distance / (velocityMadeGood * 0.514444) * 1000
This falsely assumes that VMG is in kts when it is (and should be) in m/s.
=> Fix: estimatedTimeOfArrival, timeToGo and eta calculated incorrectly in eta.js

calcs/trueWind.js
In trueWind.js derived values are now set to null in case that the input is null. Before an AWS of null resulted in a TWS of 0.
=> fix: In trueWind.js derived values are now set to null in case that the input is null.

calcs/cpa_tcpa.js
This PR
- moves the check for the age of the other vessel's position prior to calculating distanceToSelf, so that no distanceToSelf value is calculated and sent for vessels that have timed out
- adds sending null values for paths `closestApproach` and `distanceToSelf` once for vessels that have timed out 
Fixes #149
=> Fix: other vessels data updating beyond timeout for their data

calcs/cpa_tcpa.js
Add the positions of self and the other vessels to the CPA notification, so that the payload is
```
{
"state": "alert",
"method": [
"visual",
"sound"
],
"message": "Crossing vessel (unknown) 86.06 m away in 10.25  minutes",
"cpaPositions": {
"self": {
"lat": 60.0683170956023,
"lon": 23.51944354234765
},
"other": {
"lat": 60.06791079115338,
"lon": 23.520767179014822
}
},
"timestamp": "2025-02-20T19:26:26.649Z"
}
```
=> feature: add CPA positions to notifications

calcs/cpa_tcpa.js
- fix small memory leak: don't keep all notified vessel's ids
- fix clearing notifications: The code was sending the normal state notification to the other vessel, when in fact the context must be self, where the original notification was raised
- clear notifications for timed out vessels
- add other vessel's id explicitly to the notification payload
=> Cpa improvements
