SignalK/signalk-derived-data

- index.js
I suspect this is not the correct way of doing this but it reduced multiple calculations of the same data.
It checks to see if the output has changed and if not doesn't emit the diff, unless a configurable timeout has passed. Any diffs that really are diffs are emitted.
> Added a Bacon statement to remove duplicate diffs 

- calcs/tankVolume.js
> Fix Tankcalibration

- calcs/dewPoint.js
A bit quick there. Should be Math.log
> fix logarithm error

- calcs/leeway.js
As discussed in #5 , there is a formula for calculating leeway, so here it is
> Add leeway calculator

- index.js
Closes #24 
Depends on https://github.com/SignalK/signalk-server-node/pull/602
> feature: make calculation groups collapsible in the config ui

- calcs/dewPoint.js
As pointed out by Charlie at Slack
> fix: dewPoint conversions were wrong way

- README.md
- calcs/heatIndex.js
verified against their table. Closes #38
> feature: add Heat Index based on NWS formula

- calcs/tankVolume.js
Trying to get this calc to work again I disovered this error in the path
> fix: incorrect path to tank level

- calcs/tankVolume.js
> fix tank level path remaining from  #45

- calcs/magneticVariation.js
- package.json
Adds magentic variation based on position and the World Magnetic Model.
> feature: add magnetic variation

- README.md
- calcs/distanceToGo.js
Added Distance To Go calculation that uses `courseGreatCircle.nextPoint.position` to calculate distance from vessel location.
> feature: add DTG calculation

- calcs/vmg_wind.js
Using angleTrueWater instead of directionTrue
> fix: change vmg_wind input from direction to angle

- calcs/cpa_tcpa.js
- package.json
Fixes #48 by using package geolocation-utils instead of motionpredict.
> redo cpa and tcpa calculation

- package.json
> Geolib update

- calcs/cpa_tcpa.js
Old function gives error as reported on Slack
> fix: geolib functions changed after update

- calcs/dewPoint.js
- index.js
Dew point is a useful value for inside areas as well. Building on previous instance logic
> Dew point instances

- calcs/courseData.js
GH-84 Check if latitude and longitude are valid before computing course data
> Check if latitude and longitude are valid before computing course data

- calcs/courseData.js
- index.js
This PR is to address the https://github.com/SignalK/signalk-server/issues/1302 discussion.
Fixes #82.
> feature: Remove timestamp from delta update

- calcs/transducerToKeel.js
…nsducer and design.draft.maximum)
> Add calculation for transducer to keel

- calcs/propslip.js
- test/test.js
Adds also minimal test for this.
> fix: guard against 0 revs in propslip

- README.md
- calcs/courseOverGroundTrue.js
Added deriving navigation.courseOverGroundTrue from navigation.courseOverGroundMagnetic and navigation.magneticVariation.
The calculation code si similar to headingTrue.js
> COG True based on COG Magnetica and Magnetic Variation

- README.md
- calcs/courseOverGroundMagnetic.js
…cVariation
More straight forward PR only adding new courseOverGroundMagnetic calc and updating README.md
Deleting PR #95 which including group changes and typo fixes.
> feature: add calc for courseOverGroundMagnetic

- README.md
- calcs/setDrift.js
replacement PR from clean master branch
> feature: calculate set and drift

- calcs/vmg_wind.js
Beat and gybe VMGs are just positive and negative VMGs. They are not in the spec and serve no purpose?
> fix:  remove unnecessary deltas from VMG_wind

- calcs/leewayAngle.js
Calculate leeway angle from hdg and cog. Same data path as in leeway.js
> Calc leeway angle from hdg cog

- calcs/vmg_wind.js
- calcs/vmg_wind_stw.js
Alternate VMG calculation using STW instead of SOG
> VMG using wind and speedThroughWater

- calcs/propState.js
Calculate propulsion.*.state based on propulsion.*.revolutions
> Calculate propulsion..state based on propulsion..revolutions

- calcs/courseOverGroundMagnetic.js
- calcs/courseOverGroundTrue.js
- calcs/headingTrue.js
- calcs/setDrift.js
- calcs/windDirectionMagnetic.js
Null magneticVariation was not handled properly in all relevant conversions, this PR fixes that and fixes #136.
> Fix: handling of null magneticVariation

- calcs/tankVolume.js
Add capacity calculation in addition to volume
> Add capacity to  tankVolume.js

- README.md
- calcs/setDrift.js
- package.json
This PR adds: 
- Drift impact path and value (the drift's contribution to boat movement)
- Edge test cases
Fixes:
- Validation for edge case 
- Documentation typo
> Fix: Add Drift impact (set / drift)

- calcs/steer_error.js
- Update steer error to use Course API path `navigation.course.calcValues.bearingTrue`.
- Added input value validation.
> Update steer error use course API path

- index.js
- package.json
Update the icons that indicate the presence of a path value to show when the value is `null`. 
(fixes #147 )
> Add indication that path is present with a `null` value

- calcs/leewayAngle.js
- package.json
Update leeway angle calculation to use headingTrue.
(closes #112)
> Update leeway angle calculation to use headingTrue.
